version: '3.8'

services:
  backend:
      build: ./autonomo-connect-back
      container_name: autonomo-back
      ports:
        - "8000:8000"
      volumes:
        # Sincroniza código local com container (Hot Reload do Python)
        - ./autonomo-connect-back:/app
      # # Dependência: O back só inicia depois que o front estiver ok (opcional, mas organiza)
      # depends_on:
      #   - frontend
      
  frontend:
    image: node:20-alpine
    container_name: autonomo-front
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./autonomo-connect-front:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn dev --host"