server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # O segredo para SPA (Single Page Applications):
        # Tenta servir o arquivo solicitado ($uri),
        # Se não achar, tenta servir como diretório ($uri/),
        # Se falhar, serve o index.html (React Router assume daqui).
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}